### ISSUE TITLE
LUA Error

### ISSUE THREAD

**Issue by fubaWoW** [runningbird/Mythic-Plus-Key-Announcer#19]
hi there,
got an error on get invite to a Premade Group for Timewalk Firelands, error here:

```LUA
1x bad argument #1 to '?' (Usage: local activityInfo = C_LFGList.GetActivityInfoTable(activityID [, questID, showWarmode]))
[string "=[C]"]: in function `GetActivityInfoTable'
[string "@LFGMPLUSGROUP/LFGMPLUSGROUP.lua"]:35: in function `?'
[string "@TomTom/libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:109: in function <...Tom/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:109>
[string "=[C]"]: ?
[string "@TomTom/libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:19: in function <...Tom/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:15>
[string "@TomTom/libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:54: in function `Fire'
[string "@TomTom/libs/AceEvent-3.0-4/AceEvent-3.0.lua"]:120: in function <...aceTomTom/libs/AceEvent-3.0/AceEvent-3.0.lua:119>

Locals:
(*temporary) = "bad argument #1 to '?' (Usage: local activityInfo = C_LFGList.GetActivityInfoTable(activityID [, questID, showWarmode]))"

```

maybe missing "nil" check for ``activityID`` could be the problem?

i try with ``if searchResultInfo and searchResultInfo.activityID and type(searchResultInfo.activityID == 'number') then`` and report again if the error occurs again

**Comment by runningbird** [comment]
I just updated the ACE Libs to the latest so this should be fixed.

**Comment by fubaWoW** [comment]
> I just updated the ACE Libs to the latest so this should be fixed. 

So far, I haven't encountered any errors with the ``nil`` checks i have suggested above, and honestly, nil checks are always a good practice. 😊

That said, updating the ACE Libs isn’t really a proper fix for this issue as of ``C_LFGList.GetSearchResultInfo`` is not an ACE function, so updating the ACE Libs probably won’t fix anything in this case.
The ``searchResultInfo.activityID`` can still be ``nil`` if something goes wrong, and there’s no check for that!


As for the ``type`` check, it’s probably unnecessary because if this isn’t a number, then something major is already broken.
Still, there’s no harm in adding checks for all possible failures. 😉

greetings

**Comment by runningbird** [comment]
Just tested again and it's finally fixed.
